### ISSUE TITLE
Yin Yang Coin - Game Logic

### ISSUE THREAD

**Issue by vanvansan** [cse110-sp23-group21/map-my-future#31]
- The game uses a pseudo-random coin flip for users. 
 1. Draw a random option-answer pair from the dictionary JSON
 2. generate the coin-flip according to the `option`
 3. output answer

**Comment by gilkeidar** [comment]
The current game logic is being implemented as the following:

The user tosses 3 coins 6 times to produce a hexagram which is represents a particular fortune.

Each time the “Toss Coins” button is pressed, a function is run that maintains a counter (to know how many times the button has been pressed), and the `FortuneEngine` class is used to generate the result of the 3 coin flip. 

There are 8 possible 3-coin flips, each of which are mapped to a straight line (0) or a broken line (1).

Based on the resulting line, we add `0 * 2^i` or `1 * 2^i` to the hexagram index where `i` is the number of times the button has been pressed.

Once the user tossed the coins 6 times, we use the hexagram index as an index to the array of hexagram objects in the mini-app's JSON file and display it to the user.
