### ISSUE TITLE
Yin Yang Coin - Coin Flip Animation

### ISSUE THREAD

**Issue by vanvansan** [cse110-sp23-group21/map-my-future#32]
toss the coin and show the result (make the process long)

**Comment by vanvansan** [comment]
Further choice - choose 1/2/3/6 coins each time (need 6 coins to show the result)

**Comment by gilkeidar** [comment]
**Modification** - we are not implementing a choice of how many coins to flip (the user always flips 3 coins 6 times to get their reading)

**Comment by fillna** [comment]
- Display 3 coins (ideally the yin-yang symbol design) on the center of the content box.
- When "toss" clicked, all coins rotates for ~3 seconds then stop.
- There exists 2 terminal states for coin rotation: Yin/Tail - black over white; Yang/Head - white over black.
- There exists 4 distinct combinations of coins states: HHH, HHT, HTT, TTT.  **Order does NOT matter.**

NOTEs:
- The terminal states gets reduced to 2 for now to reduce implementation complexity.
- Combination gets reduced to 4 to reduce implementation complexity.
