### ISSUE TITLE
Yin Yang Coin - Frontend Tasks

### ISSUE THREAD

**Issue by vanvansan** [cse110-sp23-group21/map-my-future#33]
1. Flip
2. Number of coins to flip (1/2/3/6)
3. music
4. volume
5. info (explaination)
6. background

**Comment by gilkeidar** [comment]
**Modification** - we are not implementing a choice of how many coins to flip (the user always flips 3 coins 6 times to get their reading)

**Comment by gilkeidar** [comment]
**Update:**

The following tasks are left to do:

- [x] Update Yin Yang Coin instructions (make them sufficiently clear for a user who doesn't know anything about this fortune-telling method can understand them)
- [x] Add sound effect for when a line appears
- [x] Add sound effect for receiving the hexagram
- [x] Add sound effect when pressing action button
