### ISSUE TITLE
Yin Yang Coin - Basic UI

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#46]
Design Reference / Ideas: https://miro.com/app/board/uXjVMDrcGS8=/#tpicker-content

Implement the pages for the 4 UI Screens:

- [x] Title Screen
- [x] Rules Screen
- [x] Fortune Telling Screen
- [x] Results Screen

**Comment by minhnhat1901** [comment]
Change to 3 windows.
- [x] Welcome/Instructions Screen
- [x] Fortune Telling Screen
- [x] Results Screen

Reference: https://www.figma.com/file/mZ8gDgAVtluzmwwazUJTfL/Yin-Yang-Coin?type=design&node-id=1%3A6&t=PvwubPClY4jTZ0kj-1
