### ISSUE TITLE
Autoplay Music Problems

### ISSUE THREAD

**Issue by IllusiveAldebaran** [cse110-sp23-group21/map-my-future#50]
In the `fortune-stick` app, and to an extent the other UIs as well, the autplaying music does not play without throwing an error or not playing at all: 

`Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted.` - firefox warning
`Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.` - firefox error
`Uncaught (in promise) DOMException: play() failed because the user fortune_stick.js:18`  - Chromium based Error

Possibly look into adding a try catch block. Or how autplaying is done [elsewhere](https://developer.chrome.com/blog/autoplay/#webaudio)

**Comment by justin-chiang** [comment]
Added try catch for autoplay; if the browser fails to autoplay music, the music toggle will be set to off by default. Then, clicking it will interact with the DOM, and the music then successfully plays.
