### ISSUE TITLE
Multiple Cards Stacking in Choosing Cartomancy cards

### ISSUE THREAD

**Issue by IllusiveAldebaran** [cse110-sp23-group21/map-my-future#57]
Can stack cards to read instead of 1 in each of the three slots. Instead you can just stack all of them in 1. Or break it in other ways.

**Comment by Mchellei** [comment]
Fixed stacking issue. Now each plate only accepts one card from all decks.

**Comment by maarongross** [comment]
Stacking issue still present

**Comment by Mchellei** [comment]
Fixed.
