### ISSUE TITLE
Update CSS units --> Change all to relative units like `vh` or `vw`

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#59]
**Task Description:** Replace all instances of `px` or other absolute units with relative equivalents such as `vh` (1% of the height of the viewport) and `vw` (1% of the width of the viewport). 

Ideally, all screens with the same aspect ratios should display our app the same way, and this is a way to accomplish that.

Here's a reference to CSS units - ideally, all units used should be under the Relative Lengths heading: https://www.w3schools.com/cssref/css_units.php

**Comment by Mchellei** [comment]
Fixed all relevant instances of absolute unites to relative equivalent.
