### ISSUE TITLE
Main Page Advanced Design/Animation

### ISSUE THREAD

**Issue by fillna** [cse110-sp23-group21/map-my-future#61]
Urgent & Easy
- [x] Add main page name.
- [x] Remove non-useful map-dragging feature.
- [x] Change background image to blank treasure map.

Good to have & Intermediate 
- [ ] Add page transitions.
- [x] Add pop-up side panels including instruction/intro to each mini-app.

**Comment by gilkeidar** [comment]
I would the following:

Urgent & (hopefully) Easy:
- [x] Change background image (current one is too pixelated but has the right idea)
- [x] Wider side bar

Nice to haves:
- [x] Cursor should change to pointer when hovering over continent
- [x] Add a sfx when clicking on a continent (e.g. a sidebar "swish" sound when it shows up and leaves)
- [ ] Add on-hover animations for each continent that changes the names to a logo (e.g., cartomancy becomes an image of a few cards)
- [ ] Add credits (e.g. our team name, list of members, link to the repository, etc.) - maybe in the info button?

**Comment by gilkeidar** [comment]
Will move the last thing to a new issue
