### ISSUE TITLE
Cartomancy - Fix Visual Bugs

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#65]
There are some visual bugs in the Yin Yang Coin mini-app. Let's do our best to fix these:

- [x] Reset button has no text
- [x] "Get result" card button doesn't appear clickable (maybe add a hover animation or turn the cursor into a clicker?)
- [ ] Text in each of the card results can overflow outside of its container
- [ ] When getting the 3 result cards, maybe hovering over the card can raise it higher so the text has more room? It might be appropriate to have shorter interpretation messages + larger font size as well to make it more readable
- [ ] Center the 3 result cards(?)

**Comment by maarongross** [comment]
Update: merging our linting branch to `dev` made a lot of visual bugs due to the path change of the `assets` folder, so now we need to update the pathing for each item that uses a path

**Comment by Mchellei** [comment]
Updated all paths and fixed most visual bugs, waiting for a review from team members to make sure it's not solely on my device.
