### ISSUE TITLE
Molybdomancy - Fix Visual Bugs

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#66]
There are some visual bugs in the Yin Yang Coin mini-app. Let's do our best to fix these:

**Note:** Add any other visual bugs to this issue in a comment.

- [x] When the fortune is displayed, it may move the emoji and the title up - maybe make the container containing the meaning scrollable? Or make the text size change relative to the container?

**Comment by minhnhat1901** [comment]
I'm not sure if this issue related to Molybdomancy or Yin Yang Coin because the title is Molybdomancy but the content is Yin Yang Coin.
