### ISSUE TITLE
Sprint 1: Answer Dictionaries

### ISSUE THREAD

**Issue by maarongross** [cse110-sp23-group21/map-my-future#7]
- part of the main function of the 8-ball engine
- the app should be able to use different answer dictionaries
- these dictionaries would correspond to various mini-apps based on different fortune telling methods

**Comment by fillna** [comment]
- A class/object/data structure that store all the answers, the actual data will be an input on the constructor.
- Have a function that randomly generate an answer. This function takes in an output_number as one of the input, enabling some of the mini-apps to generate multiple objects or so, this would default to 1.

**Comment by fillna** [comment]
- A class/object/data structure that store all the answers, the actual data will be an input on the constructor.
- Have a function that randomly generate an object. This function takes in an output_number as one of the input, enabling some of the mini-apps to generate multiple objects or so, this would default to 1.

**Comment by vanvansan** [comment]
To have a class that stores answers with member vars of Answer, member functions init(reset the dict), size(return size), answer(return answer by index passed in), answerPicked(true if the item with index has been picked before), biasOf(return the bias level of the answer if any) and etc.  

Remember to have default values. Implementations are up to you. More things will be added to issues later.
