### ISSUE TITLE
Move `assets` folder into `src`

### ISSUE THREAD

**Issue by gilkeidar** [cse110-sp23-group21/map-my-future#76]
This is a necessary step for deployment.

**Note:** This change _will_ break a bunch of asset paths. Part of completing this issue is making sure this move is accomplished without any errors! I.e., all asset paths should be fixed before this issue is marked as "closed."

**Comment by fillna** [comment]
- [x] Update file path for `fortune-stick`.
- [x] Update file path for `cartomancy`.
- [x] Update file path for `yin-yang-coin`.
- [x] Update file path for `molybdomancy`.
- [x] Update file path for home page.
