### ISSUE TITLE
Sprint 1: Testing for the engine

### ISSUE THREAD

**Issue by vanvansan** [cse110-sp23-group21/map-my-future#8]

**Comment by vanvansan** [comment]
choose the test type

**Comment by gilkeidar** [comment]
**Requirement:** Add test cases to test the `FortuneEngine` class.

Ideas for tests:
- Test that you can read a JSON file and that its array value matches the `this.outcomes` array
- Test that when calling `getRandomSubset(n)`, you get an array of `n` objects, all of which are elements of `this.outcomes`
